spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ticket_app
    username: postgres
    password: mysecretpassword
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/ticketing_app
      client:
        registration:
          keycloak:
            client-id: ticket-app-client
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/ticketing_app
            user-name-attribute: preferred_username

logging:
  level:
    org.springframework.security: debug

server:
  port: 8081