spring:
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: mysecretpassword
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/ticketing_app
      client:
        registration:
          keycloak:
            client-id: ticket-app-client
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://keycloak:8080/realms/ticketing_app
            user-name-attribute: preferred_username

management:
  tracing:
    sampling:
      probability: 1.0 # sampling all in dev, reduce it in prod to save loading
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

keycloak:
  resource: ticket-app-client
  auth-server-url: http://localhost:8080/realms/ticketing_app/protocol/openid-connect/auth
  realm: ticketing_app

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

server:
  port: 8081