version: '2'

services:
  db:
    image: 'postgres:latest'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
  server:
    image: 'ticketing:latest'
    build:
      context: .
    container_name: server
    depends_on:
      - db
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres'
      - 'SPRING_DATASOURCE_USERNAME=postgres'
      - 'SPRING_DATASOURCE_PASSWORD=mysecretpassword'
      - 'SPRING_JPA_HIBERNATE_DDL_AUTO=create'
    ports:
      - "8081:8081"
