version: '2'

services:
  db:
    image: 'postgres:latest'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - '5432:5432'
  keycloak:
    image: 'quay.io/keycloak/keycloak:latest'
    container_name: keycloak
    command: -v start-dev --import-realm
    volumes:
      - ./imports:/opt/keycloak/import
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_IMPORT=/opt/keycloak/import
    ports:
      - '8080:8080'
  server:
    image: 'ticketing:latest'
    build:
      context: .
    container_name: server
    depends_on:
      - db
      - keycloak
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres'
      - 'SPRING_DATASOURCE_USERNAME=postgres'
      - 'SPRING_DATASOURCE_PASSWORD=mysecretpassword'
      - 'SPRING_JPA_HIBERNATE_DDL_AUTO=create'
    ports:
      - "8081:8081"