version: '3.4'

services:
  db:
    image: 'postgres:latest'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - '5432:5432'

  keycloak:
    image: 'quay.io/keycloak/keycloak:latest'
    container_name: keycloak
    command: -v start-dev --import-realm
    volumes:
      - ./imports:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_IMPORT=/opt/keycloak/data/import
    ports:
      - '8080:8080'

  server:
    image: 'ticketing:latest'
    build:
      context: .
    container_name: server
    ports:
      - "8081:8081"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
      - keycloak