version: '3.1'

services:
  db:
    image: 'postgres:latest'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - '5432:5432'
  keycloak:
    image: 'quay.io/keycloak/keycloak:latest'
    container_name: keycloak
    command: -v start-dev --import-realm
    volumes:
      - ./imports:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_IMPORT=/opt/keycloak/data/import
    ports:
      - '8080:8080'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 1000
  server:
    image: 'ticketing:latest'
    build:
      context: .
    container_name: server
    environment:
      - 'SPRING_JPA_HIBERNATE_DDL_AUTO=create'
    ports:
      - "8081:8081"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 5
        window: 60s