version: '3.1'

services:

  tempo:
    image: 'grafana/tempo:latest'
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./observer/tempo/tempo-local.yaml:/etc/tempo.yaml:ro
      - ./tempo-data:/tmp/tempo
    ports:
      - "14268"  # jaeger ingest
      - "9411:9411" # zipkin
    hostname: tempo
    deploy:
      replicas: 0

  loki:
    image: 'grafana/loki:latest'
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    ports:
      - "3100:3100"                                   # loki needs to be exposed so it receives logs
    environment:
      - JAEGER_AGENT_HOST=tempo
      - JAEGER_ENDPOINT=http://tempo:14268/api/traces # send traces to Tempo
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    hostname: loki
    deploy:
      replicas: 0

  prometheus:
    image: 'prom/prometheus:latest'
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    command:
      - --enable-feature=exemplar-storage
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./observer/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    hostname: prometheus
    deploy:
      replicas: 0

  grafana:
    image: 'grafana/grafana:latest'
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    volumes:
      - ./observer/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./observer/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
    hostname: grafana
    deploy:
      replicas: 0

  db:
    image: 'postgres:latest'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - '5432:5432'
    hostname: db

  keycloak:
    image: 'quay.io/keycloak/keycloak:latest'
    container_name: keycloak
    command: -v start-dev --import-realm
    volumes:
      - ./imports:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_IMPORT=/opt/keycloak/data/import
    ports:
      - '8080:8080'
    hostname: keycloak

  server:
    image: 'ticketing:latest'
    build:
      context: .
    container_name: server
    environment:
      - 'SPRING_JPA_HIBERNATE_DDL_AUTO=create'
    ports:
      - "8081:8081"
    hostname: server
    deploy:
      replicas: 0